version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    depends_on: 
      - db
    ports:
        - 80:80
    networks: 
      bridge_network:
        ipv4_address: 172.100.18.2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
# define the wordpress container
  db:
    image: mysql:latest
    container_name: mysql-container
    networks: 
      bridge_network:
        ipv4_address: 172.100.18.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
# define the myswl container
  loadbalancer-nginx:
# define the nginx-container
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80 # exposed port
    depends_on: 
      - db
      - wordpress
    networks:
      bridge_network:
        ipv4_address: 172.100.18.4

networks:
# define the networks
  bridge_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.100.18.0/24

volumes:
  wordpress:
